# Generated by Django 5.1.7 on 2025-03-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.PositiveSmallIntegerField(default=2000, max_length=4),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
