# Generated by Django 5.1.7 on 2025-04-02 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesWeb', '0004_movie_description_movie_imdb_rating_movie_poster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
    ]
