# Generated by Django 5.1.7 on 2025-04-03 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesWeb', '0006_moreinfo_movie_more_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moreinfo',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Komedia'), (3, 'Horror'), (1, 'Dramat'), (5, 'Akcja'), (0, 'Inne'), (4, 'Sci-Fi'), (6, 'Fantasy')], default=0),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(blank=True, default='')),
                ('rating_point', models.PositiveSmallIntegerField(default=5)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoviesWeb.movie')),
            ],
        ),
    ]
