# Generated by Django 5.1.7 on 2025-04-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesWeb', '0007_alter_moreinfo_genre_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moreinfo',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Dramat'), (3, 'Horror'), (6, 'Fantasy'), (0, 'Inne'), (4, 'Sci-Fi'), (2, 'Komedia'), (5, 'Akcja')], default=0),
        ),
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=32)),
                ('character', models.CharField(max_length=32)),
                ('movies', models.ManyToManyField(to='MoviesWeb.movie')),
            ],
        ),
    ]
