# Generated by Django 5.1.7 on 2025-04-03 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesWeb', '0009_remove_cast_character_alter_moreinfo_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='comments',
        ),
        migrations.AlterField(
            model_name='moreinfo',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Dramat'), (0, 'Inne'), (4, 'Sci-Fi'), (6, 'Fantasy'), (5, 'Akcja'), (3, 'Horror'), (2, 'Komedia')], default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating_point',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
