# Generated by Django 5.1.7 on 2025-04-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesWeb', '0010_remove_movie_comments_alter_moreinfo_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='cast',
            name='movies',
            field=models.ManyToManyField(related_name='actors', to='MoviesWeb.movie'),
        ),
        migrations.AlterField(
            model_name='moreinfo',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Inne'), (2, 'Komedia'), (1, 'Dramat'), (5, 'Akcja'), (3, 'Horror'), (4, 'Sci-Fi'), (6, 'Fantasy')], default=0),
        ),
    ]
